export interface PaletteItem {
  label: string
  desc: string
  nodeType: string
  dotClass: string
  component: string
  defaultSize: {
    w: number
    h: number
  }
  defaultProps: Record<string, unknown>
}

export interface PaletteGroup {
  label: string
  items: PaletteItem[]
}

export const PaletteList: PaletteGroup[] = [
  {
    label: '基础组件',
    items: [
      {
        label: '矩形',
        desc: '基础容器',
        nodeType: 'basic',
        dotClass: 'bg-sky-500',
        component: 'rect',
        defaultSize: {
          w: 280,
          h: 160,
        },
        defaultProps: {
          text: '矩形容器',
        },
      },
      {
        label: '圆形',
        desc: '指标展示',
        nodeType: 'basic',
        dotClass: 'bg-emerald-500',
        component: 'circle',
        defaultSize: {
          w: 120,
          h: 120,
        },
        defaultProps: {
          text: '圆形指标',
        },
      },
      {
        label: '文本',
        desc: '说明文字',
        nodeType: 'basic',
        dotClass: 'bg-amber-500',
        component: 'text',
        defaultSize: {
          w: 220,
          h: 56,
        },
        defaultProps: {
          text: '文本标题',
        },
      },
      {
        label: '数据卡',
        desc: '单值指标卡片',
        nodeType: 'basic',
        dotClass: 'bg-cyan-500',
        component: 'metricCard',
        defaultSize: {
          w: 320,
          h: 180,
        },
        defaultProps: {
          text: '核心指标',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '进度条',
        desc: '进度状态展示',
        nodeType: 'basic',
        dotClass: 'bg-orange-500',
        component: 'progressBar',
        defaultSize: {
          w: 320,
          h: 160,
        },
        defaultProps: {
          text: '执行进度',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '边框装饰',
        desc: '科技感面板边框容器',
        nodeType: 'basic',
        dotClass: 'bg-indigo-500',
        component: 'borderBox',
        defaultSize: {
          w: 320,
          h: 240,
        },
        defaultProps: {
          text: '边框容器',
        },
      },
      {
        label: '时间天气',
        desc: '系统时钟与环境天气',
        nodeType: 'basic',
        dotClass: 'bg-amber-400',
        component: 'timeWeather',
        defaultSize: {
          w: 360,
          h: 80,
        },
        defaultProps: {
          text: '时间天气看板',
        },
      },
      {
        label: '工业流程图',
        desc: '智慧矿山 2.5D 动态连接流程图',
        nodeType: 'basic',
        dotClass: 'bg-sky-500',
        component: 'mineProcessMap',
        defaultSize: {
          w: 800,
          h: 500,
        },
        defaultProps: {
          text: '矿山生产流程图',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
    ],
  },
  {
    label: '图表',
    items: [
      {
        label: '柱状图',
        desc: '数据统计图表',
        nodeType: 'chart',
        dotClass: 'bg-violet-500',
        component: 'chart',
        defaultSize: {
          w: 360,
          h: 240,
        },
        defaultProps: {
          text: '柱状图',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '折线图',
        desc: '趋势变化展示',
        nodeType: 'chart',
        dotClass: 'bg-cyan-500',
        component: 'lineChart',
        defaultSize: {
          w: 420,
          h: 240,
        },
        defaultProps: {
          text: '折线趋势图',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '饼图',
        desc: '比例展示',
        nodeType: 'chart',
        dotClass: 'bg-cyan-500',
        component: 'pieChart',
        defaultSize: {
          w: 420,
          h: 240,
        },
        defaultProps: {
          text: '饼图',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '排行榜',
        desc: 'TOP 列表展示',
        nodeType: 'chart',
        dotClass: 'bg-fuchsia-500',
        component: 'rankingList',
        defaultSize: {
          w: 360,
          h: 320,
        },
        defaultProps: {
          text: '排行看板',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '告警列表',
        desc: '事件告警展示',
        nodeType: 'chart',
        dotClass: 'bg-rose-500',
        component: 'alertList',
        defaultSize: {
          w: 360,
          h: 320,
        },
        defaultProps: {
          text: '告警列表',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '仪表盘',
        desc: '指标刻度盘展示',
        nodeType: 'chart',
        dotClass: 'bg-cyan-500',
        component: 'gauge',
        defaultSize: {
          w: 320,
          h: 240,
        },
        defaultProps: {
          text: '仪表盘',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '状态网格',
        desc: '多设备运行状态指示',
        nodeType: 'chart',
        dotClass: 'bg-emerald-500',
        component: 'statusGrid',
        defaultSize: {
          w: 360,
          h: 240,
        },
        defaultProps: {
          text: '设备状态网格',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '雷达图',
        desc: '多维数据特征对比',
        nodeType: 'chart',
        dotClass: 'bg-violet-500',
        component: 'radarChart',
        defaultSize: {
          w: 360,
          h: 280,
        },
        defaultProps: {
          text: '多维特征雷达图',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '横向柱状图',
        desc: '横向对比统计图表',
        nodeType: 'chart',
        dotClass: 'bg-blue-500',
        component: 'horizontalBar',
        defaultSize: {
          w: 360,
          h: 240,
        },
        defaultProps: {
          text: '横向排行图表',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '环形进度仪',
        desc: '圆环比例进度展示',
        nodeType: 'chart',
        dotClass: 'bg-cyan-500',
        component: 'ringProgress',
        defaultSize: {
          w: 240,
          h: 240,
        },
        defaultProps: {
          text: '环形进度仪',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '滚动日志表',
        desc: '多列动态列表展示',
        nodeType: 'chart',
        dotClass: 'bg-emerald-500',
        component: 'scrollTable',
        defaultSize: {
          w: 380,
          h: 300,
        },
        defaultProps: {
          text: '实时运行日志表',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
    ],
  },
  {
    label: '平面图设备',
    items: [
      {
        label: '变压器',
        desc: '变电与配电核心设备',
        nodeType: 'device',
        dotClass: 'bg-yellow-500',
        component: 'topologyDevice',
        defaultSize: {
          w: 120,
          h: 140,
        },
        defaultProps: {
          text: '主变压器',
          deviceType: 'transformer',
          status: 'running',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '储能电池',
        desc: '电池储能与充放电模组',
        nodeType: 'device',
        dotClass: 'bg-emerald-500',
        component: 'topologyDevice',
        defaultSize: {
          w: 120,
          h: 140,
        },
        defaultProps: {
          text: '储能电池组',
          deviceType: 'battery',
          status: 'running',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '配电柜',
        desc: '低压配电与控制柜',
        nodeType: 'device',
        dotClass: 'bg-blue-500',
        component: 'topologyDevice',
        defaultSize: {
          w: 120,
          h: 140,
        },
        defaultProps: {
          text: '动力配电柜',
          deviceType: 'cabinet',
          status: 'running',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '不间断电源 UPS',
        desc: '应急备用电源控制单元',
        nodeType: 'device',
        dotClass: 'bg-cyan-500',
        component: 'topologyDevice',
        defaultSize: {
          w: 120,
          h: 140,
        },
        defaultProps: {
          text: 'UPS 电源箱',
          deviceType: 'ups',
          status: 'running',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '服务器机柜',
        desc: '数据中心标准 IT 机柜',
        nodeType: 'device',
        dotClass: 'bg-slate-500',
        component: 'topologyDevice',
        defaultSize: {
          w: 120,
          h: 140,
        },
        defaultProps: {
          text: 'IT 服务器柜',
          deviceType: 'rack',
          status: 'running',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '空调冷机',
        desc: '精密温控与制冷风机',
        nodeType: 'device',
        dotClass: 'bg-teal-400',
        component: 'topologyDevice',
        defaultSize: {
          w: 120,
          h: 140,
        },
        defaultProps: {
          text: '精密空调',
          deviceType: 'chiller',
          status: 'running',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '柴油发电机',
        desc: '后备重力柴发系统',
        nodeType: 'device',
        dotClass: 'bg-amber-600',
        component: 'topologyDevice',
        defaultSize: {
          w: 120,
          h: 140,
        },
        defaultProps: {
          text: '备用发电机',
          deviceType: 'generator',
          status: 'stopped',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
    ],
  },
  {
    label: '2.5D 矿山设备',
    items: [
      {
        label: '主/副竖井塔',
        desc: '巨型矿山井架与配料塔',
        nodeType: 'mine_device',
        dotClass: 'bg-indigo-500',
        component: 'mineDevice',
        defaultSize: {
          w: 180,
          h: 220,
        },
        defaultProps: {
          text: '东晋主竖井系统',
          deviceType: 'shaft',
          status: 'running',
          value: '62.0',
          unit: 'Hz',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '金属原煤仓',
        desc: '高反光 specular 镜面储仓',
        nodeType: 'mine_device',
        dotClass: 'bg-blue-500',
        component: 'mineDevice',
        defaultSize: {
          w: 160,
          h: 180,
        },
        defaultProps: {
          text: '精矿筒仓 A',
          deviceType: 'silo_metal',
          status: 'running',
          value: '64.0',
          unit: '%',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '混凝土配煤仓',
        desc: '宽体混凝土结构缓冲仓',
        nodeType: 'mine_device',
        dotClass: 'bg-cyan-500',
        component: 'mineDevice',
        defaultSize: {
          w: 160,
          h: 180,
        },
        defaultProps: {
          text: '地表原煤仓',
          deviceType: 'silo_concrete',
          status: 'running',
          value: '64',
          unit: 'm',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '重型破碎机',
        desc: '带旋转飞轮的颚式破碎机',
        nodeType: 'mine_device',
        dotClass: 'bg-amber-500',
        component: 'mineDevice',
        defaultSize: {
          w: 180,
          h: 180,
        },
        defaultProps: {
          text: '双机圆锥破碎机',
          deviceType: 'crusher_jaw',
          status: 'running',
          value: '48.5',
          unit: 'A',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '高频振动筛',
        desc: '双层弹簧减震物料分选筛',
        nodeType: 'mine_device',
        dotClass: 'bg-teal-500',
        component: 'mineDevice',
        defaultSize: {
          w: 180,
          h: 180,
        },
        defaultProps: {
          text: '高频振动分选筛',
          deviceType: 'sifter_vibratory',
          status: 'running',
          value: '48',
          unit: 'Hz',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '皮带传送桥',
        desc: '带流光动画的钢桁架栈桥',
        nodeType: 'mine_device',
        dotClass: 'bg-sky-500',
        component: 'mineDevice',
        defaultSize: {
          w: 220,
          h: 150,
        },
        defaultProps: {
          text: '3号主斜井皮带机',
          deviceType: 'conveyor_belt',
          status: 'running',
          value: '62',
          unit: 'm/s',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '长型皮带机',
        desc: '长跨度扁平多支撑传送带',
        nodeType: 'mine_device',
        dotClass: 'bg-sky-600',
        component: 'mineDevice',
        defaultSize: {
          w: 320,
          h: 140,
        },
        defaultProps: {
          text: '1号废石转载长皮带',
          deviceType: 'conveyor_belt_long',
          status: 'running',
          value: '62',
          unit: 'm/s',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '宽型重载皮带机',
        desc: '宽幅双立柱重载矿石皮带机',
        nodeType: 'mine_device',
        dotClass: 'bg-sky-700',
        component: 'mineDevice',
        defaultSize: {
          w: 240,
          h: 160,
        },
        defaultProps: {
          text: '选厂主斜井重载皮带机',
          deviceType: 'conveyor_belt_wide',
          status: 'running',
          value: '62',
          unit: 'm/s',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '点式除尘箱',
        desc: '点式脉冲防爆除尘装置',
        nodeType: 'mine_device',
        dotClass: 'bg-emerald-500',
        component: 'mineDevice',
        defaultSize: {
          w: 140,
          h: 160,
        },
        defaultProps: {
          text: '点式除尘器',
          deviceType: 'dust_collector',
          status: 'running',
          value: '19',
          unit: 'kPa',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '重型板式给料机',
        desc: '重型耐磨板式均匀给矿机',
        nodeType: 'mine_device',
        dotClass: 'bg-amber-600',
        component: 'mineDevice',
        defaultSize: {
          w: 180,
          h: 180,
        },
        defaultProps: {
          text: '选厂重型板式给料机',
          deviceType: 'feeder_plate',
          status: 'running',
          value: '62.0',
          unit: 'Hz',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '电磁除铁器',
        desc: '带Scraper自卸式强磁除铁机',
        nodeType: 'mine_device',
        dotClass: 'bg-rose-500',
        component: 'mineDevice',
        defaultSize: {
          w: 160,
          h: 180,
        },
        defaultProps: {
          text: '悬挂电磁除铁器',
          deviceType: 'iron_remover',
          status: 'running',
          value: '正常',
          unit: '',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '袋式除尘器',
        desc: '脉冲喷吹大袋室防爆收尘机',
        nodeType: 'mine_device',
        dotClass: 'bg-teal-600',
        component: 'mineDevice',
        defaultSize: {
          w: 160,
          h: 180,
        },
        defaultProps: {
          text: '储料仓布袋除尘器',
          deviceType: 'baghouse_filter',
          status: 'running',
          value: '1.25',
          unit: 'kPa',
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '流光连接管道',
        desc: '可配置形状与颜色的流物料管道',
        nodeType: 'mine_device',
        dotClass: 'bg-blue-400',
        component: 'mineDevice',
        defaultSize: {
          w: 200,
          h: 200,
        },
        defaultProps: {
          text: '流光管道',
          deviceType: 'pipeline',
          status: 'running',
          value: '正常',
          unit: '',
          pipeShape: 'slope_up',
          pipeColor: 'cyan',
          pipeStyle: 'solid',
          transparentBg: true,
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
    ],
  },
  {
    label: '2.5D 光伏设备',
    items: [
      {
        label: '太阳能电板',
        desc: '4连排等轴侧晶硅光伏发电面板',
        nodeType: 'pv_device',
        dotClass: 'bg-sky-500',
        component: 'pvDevice',
        defaultSize: {
          w: 180,
          h: 200,
        },
        defaultProps: {
          text: '光伏发电板组',
          deviceType: 'pv_panel',
          status: 'running',
          value: '25.4',
          unit: 'kW',
          transparentBg: true,
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '光伏汇流箱',
        desc: '智能防雷防爆光伏汇流箱',
        nodeType: 'pv_device',
        dotClass: 'bg-emerald-500',
        component: 'pvDevice',
        defaultSize: {
          w: 140,
          h: 180,
        },
        defaultProps: {
          text: '智能汇流箱',
          deviceType: 'combiner_box',
          status: 'running',
          value: '315',
          unit: 'V',
          transparentBg: true,
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '光伏逆变器',
        desc: '户外高效智能光伏逆变器柜组',
        nodeType: 'pv_device',
        dotClass: 'bg-blue-600',
        component: 'pvDevice',
        defaultSize: {
          w: 150,
          h: 180,
        },
        defaultProps: {
          text: '智能逆变器',
          deviceType: 'inverter',
          status: 'running',
          value: '254.5',
          unit: 'kW',
          transparentBg: true,
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '箱式变压器',
        desc: '箱式户外集成变配电站组',
        nodeType: 'pv_device',
        dotClass: 'bg-amber-600',
        component: 'pvDevice',
        defaultSize: {
          w: 180,
          h: 180,
        },
        defaultProps: {
          text: '箱式变压器',
          deviceType: 'box_transformer',
          status: 'running',
          value: '10.5',
          unit: 'kV',
          transparentBg: true,
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
      {
        label: '并网高压电塔',
        desc: '高空特高压并网输电铁架塔',
        nodeType: 'pv_device',
        dotClass: 'bg-rose-500',
        component: 'pvDevice',
        defaultSize: {
          w: 180,
          h: 220,
        },
        defaultProps: {
          text: '并网高压电塔',
          deviceType: 'transmission_tower',
          status: 'running',
          value: '110',
          unit: 'kV',
          transparentBg: true,
          datasetId: '',
          xField: '',
          yField: '',
          refreshInterval: 0,
        },
      },
    ],
  },
]
